name: nft_observer
description: "NFT observer application"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <3.4.0"
  flutter: ">=3.19.0 <3.20.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ./core

  core_ui:
    path: ./core_ui

  navigation:
    path: ./navigation

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.4.1
  flutter_lints: ^3.0.0
  melos: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/kanit/Kanit-Black.ttf
        - asset: assets/fonts/kanit/Kanit-Bold.ttf
        - asset: assets/fonts/kanit/Kanit-ExtraBold.ttf
        - asset: assets/fonts/kanit/Kanit-ExtraLight.ttf
        - asset: assets/fonts/kanit/Kanit-Light.ttf
        - asset: assets/fonts/kanit/Kanit-Medium.ttf
        - asset: assets/fonts/kanit/Kanit-Regular.ttf
        - asset: assets/fonts/kanit/Kanit-SemiBold.ttf
        - asset: assets/fonts/kanit/Kanit-Thin.ttf