name: core
publish_to: none

environment:
  sdk: ">=3.3.0 <3.4.0"
  flutter: ">=3.19.0 <3.20.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.28.0
  firebase_analytics: ^10.10.0
  firebase_crashlytics: ^3.5.0
  get_it: ^7.7.0
  easy_localization: ^3.0.7
  device_info_plus: ^9.1.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.4.1
  flutter_lints: ^3.0.0

flutter:
  assets:
    - ../assets/translations/
