name: domain
publish_to: none

environment:
  sdk: ">=3.3.0 <3.4.0"
  flutter: ">=3.19.0 <3.20.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.4.1
  flutter_lints: ^3.0.0
