name: splash
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.3.0 <3.4.0"
  flutter: ">=3.19.0 <3.20.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core

  navigation:
    path: ../../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer: ^6.4.1
  flutter_lints: ^3.0.0
  auto_route_generator: 7.3.2
  build_runner: ^2.4.8
